### ISSUE TITLE
Ato autosplitter not splitting on scrolls

### ISSUE THREAD

**Issue by ori-sky** [TehCupcakes/AutoSplitters#1]
I've encountered an issue over the past day when trying to use the Ato autosplitter during my speedruns, where it won't autosplit on picking up any scrolls in the game., but will split on other events like picking up the blue/red/yellow shards.

I'm unsure how to find the Ato version number I'm on but it's the most recent update available to me on Steam (build ID 7587636). If I revert to the previous commit in this repository, i.e. without support for 1.0.8.0, then the scroll autosplitting begins working again.

**Comment by TehCupcakes** [comment]
Thanks for the report! I uploaded a new version of the autosplitter pre-emptively, and it turns out that even though it could detect older versions, it wasn't loading the older version's addresses; it always got the latest. This should be fixed now.
